### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by blackhatca** [raoneDEV/SearX_easy_Installer#1]
im geting this error 

Traceback (most recent call last):
  File "searx/webapp.py", line 74, in <module>
    from searx.search import SearchWithPlugins, get_search_query_from_webapp
  File "/usr/local/searx/searx/search.py", line 32, in <module>
    from searx.external_bang import get_bang_url
  File "/usr/local/searx/searx/external_bang.py", line 12, in <module>
    with open(join(searx_dir, 'data/bangs.json'), encoding='utf-8') as json_file:
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by rajee-a** [comment]
python 2 is no longer supported. You can try with python3 ?
